package ch.lkmc.goo.engine.core

import kotlin.math.cos
import kotlin.math.sin

/**
 * Fanning one stamp out into a symmetric family (proposal 0005).
 *
 * This is the same idea `BrushTool.mirrorStamp` already implements —
 * transform the stamp, not the field — with a bigger group: N rotations
 * about the image center, optionally each with its mirror twin.
 *
 * Because the copies are produced at emission and stored as ordinary
 * stamps, everything downstream sees a plain stroke: undo, redo,
 * full-resolution export replay, project persistence and GOOvie endpoint
 * caches need no symmetry logic and no format change. That is why
 * `Stroke` does NOT carry a sector count — proposal 0005 suggested one,
 * but with copies baked in at emission (as Mirror has always done) it
 * would be a second source of truth for something the stamps already
 * say.
 *
 * ### Why this composes with Mirror instead of replacing it
 *
 * The proposal claimed ×2 would be exactly today's Mirror, making the
 * dial a superset of the toggle. It is not: a true dihedral group of
 * order 2 is generated by a rotation of π, which composed with a
 * reflection gives a *horizontal* mirror, while the toggle users have is
 * a *vertical* one. Folding Mirror into the dial would therefore have
 * silently changed what an existing control does. So the dial is
 * rotational, Mirror stays reflective, and they multiply: sectors alone
 * give a pinwheel, sectors with Mirror give a true kaleidoscope with
 * mirror lines, and `sectors = 1` leaves every existing behaviour
 * bit-identical.
 */
object Symmetry {

    /** The most copies one gesture may fan into. See [expand]'s cost note. */
    const val MAX_SECTORS = 12

    /** Dial positions, in order. 1 is off. */
    val SECTORS = listOf(1, 2, 3, 4, 6, 8, 12)

    /**
     * [stamp] rotated into [sectors] copies about the image center,
     * including the original. `sectors <= 1` returns just the original,
     * allocating nothing extra.
     *
     * Rotation happens in **aspect space** — the space brush circles are
     * round in, and the space `GlobalField`'s twirl rotates in. Rotating
     * the raw UV vector instead would produce elliptical mandalas on
     * every non-square photo, which is the single likeliest way to get
     * this wrong and is invisible on a square test image.
     *
     * A copy's delta is rotated only for modes whose delta is a vector
     * ([StampMode.rotatesDelta]). VORTEX's `dx` is a chirality, and
     * rotation preserves handedness, so it rides along unchanged;
     * rotating it would corrupt a sign into a fraction.
     *
     * Copies whose center leaves the frame are kept: an off-canvas
     * center still contributes to in-canvas texels within its radius,
     * which is what makes strokes near the border blend rather than stop
     * dead. The renderer skips the ones that genuinely cannot reach
     * ([StampBounds] returns an empty rect).
     *
     * **Cost.** Every copy is a real stamp in the log, so the log and
     * every replay that reads it grow N-fold — REVIEW G-6's five-second
     * pumped hold becomes 3600 field passes at ×12. That is why the dial
     * is capped and why the checkpoint work landed first.
     */
    fun expand(tool: BrushTool, stamp: Stamp, aspect: Float, sectors: Int): List<Stamp> {
        if (sectors <= 1) return listOf(stamp)
        require(sectors <= MAX_SECTORS) { "sectors out of range: $sectors" }
        val out = ArrayList<Stamp>(sectors)
        out.add(stamp)
        // Aspect-space offset from the image center, rotated by 2πj/N.
        val ax = (stamp.cx - 0.5f) * aspect
        val ay = stamp.cy - 0.5f
        val adx = stamp.dx * aspect
        val ady = stamp.dy
        for (j in 1 until sectors) {
            val theta = TAU * j / sectors
            val c = cos(theta)
            val s = sin(theta)
            val rx = ax * c - ay * s
            val ry = ax * s + ay * c
            val rdx: Float
            val rdy: Float
            if (tool.mode.rotatesDelta) {
                rdx = (adx * c - ady * s) / aspect
                rdy = adx * s + ady * c
            } else {
                rdx = stamp.dx
                rdy = stamp.dy
            }
            // Constructed rather than `stamp.copy(...)`, matching
            // mirrorStamp. Every field of a Stamp is geometric, so if one
            // is ever added, a copy would carry it through a rotation
            // untransformed and silently wrong; naming them all makes
            // that a compile error and a decision instead.
            out.add(Stamp(cx = 0.5f + rx / aspect, cy = 0.5f + ry, dx = rdx, dy = rdy))
        }
        return out
    }

    /**
     * The full family for one emitted stamp: [sectors] rotations, each
     * with its mirror twin when [mirrored]. The order is deliberate —
     * rotate first, then mirror each copy — because warp-of-warp
     * composition is ordered, and a stroke must replay in the order it
     * was stamped.
     */
    fun family(
        tool: BrushTool,
        stamp: Stamp,
        aspect: Float,
        sectors: Int,
        mirrored: Boolean,
    ): List<Stamp> {
        val rotated = expand(tool, stamp, aspect, sectors)
        if (!mirrored) return rotated
        val out = ArrayList<Stamp>(rotated.size * 2)
        for (s in rotated) {
            out.add(s)
            out.add(tool.mirrorStamp(s))
        }
        return out
    }
}
