package ch.lkmc.goo.ui.home

import android.graphics.BitmapFactory
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.PickVisualMediaRequest
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.navigationBarsPadding
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import ch.lkmc.goo.BuildConfig
import ch.lkmc.goo.R
import ch.lkmc.goo.ui.components.ChromeButton
import ch.lkmc.goo.ui.components.GridBackdrop
import ch.lkmc.goo.ui.components.Wordmark
import ch.lkmc.goo.ui.theme.MeltPanel
import ch.lkmc.goo.ui.theme.NeonCyan
import ch.lkmc.goo.ui.theme.NeonMagenta
import ch.lkmc.goo.ui.theme.chromeSweep
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * The In room: a console standing on a neon horizon, with one giant
 * button into the goo. The system Photo Picker needs no permission and no
 * gallery UI of our own — Meltorama is an editor, not a browser
 * (PLAN.md §1). Below the door: bundled samples for instant play
 * (PLAN.md §6.1), procedurally generated by scripts/generate_samples.py.
 */
@Composable
fun HomeScreen(onOpenImage: (Uri) -> Unit) {
    val pickImage = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.PickVisualMedia(),
    ) { uri -> uri?.let(onOpenImage) }

    var showAbout by remember { mutableStateOf(false) }
    if (showAbout) {
        AlertDialog(
            onDismissRequest = { showAbout = false },
            title = { Text(stringResource(R.string.about_title, BuildConfig.VERSION_NAME)) },
            text = { Text(stringResource(R.string.about_body)) },
            confirmButton = {
                TextButton(onClick = { showAbout = false }) {
                    Text(stringResource(R.string.about_close))
                }
            },
        )
    }

    Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) {
        Box(modifier = Modifier.fillMaxSize()) {
            GridBackdrop()
            TextButton(
                onClick = { showAbout = true },
                modifier = Modifier
                    .align(Alignment.BottomCenter)
                    // Edge-to-edge (MainActivity): without the inset the
                    // 3-button nav bar would cover most of this button.
                    .navigationBarsPadding()
                    .padding(bottom = 24.dp),
            ) {
                Text(
                    text = stringResource(R.string.home_about),
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(32.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.Center,
            ) {
                Wordmark(
                    name = stringResource(R.string.app_name_full),
                    model = stringResource(R.string.app_model),
                )
                Spacer(modifier = Modifier.height(10.dp))
                // The claim, set like a slogan stamped on the bezel.
                Text(
                    text = stringResource(R.string.home_tagline),
                    style = MaterialTheme.typography.titleMedium,
                    color = NeonCyan,
                    textAlign = TextAlign.Center,
                )
                Spacer(modifier = Modifier.height(6.dp))
                Text(
                    text = stringResource(R.string.home_subtagline),
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    textAlign = TextAlign.Center,
                )
                Spacer(modifier = Modifier.height(36.dp))
                ChromeButton(
                    label = stringResource(R.string.home_enter_goo),
                    color = NeonMagenta,
                    onClick = {
                        pickImage.launch(
                            PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly),
                        )
                    },
                    size = 128.dp,
                    breathe = true,
                )
                Spacer(modifier = Modifier.height(32.dp))
                Text(
                    text = stringResource(R.string.home_samples_label),
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                Spacer(modifier = Modifier.height(12.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(20.dp)) {
                    SampleThumb(
                        assetPath = "samples/goo-guy.png",
                        labelRes = R.string.sample_goo_guy,
                        glow = NeonMagenta,
                        onOpenImage = onOpenImage,
                    )
                    SampleThumb(
                        assetPath = "samples/candy-blobs.png",
                        labelRes = R.string.sample_candy_blobs,
                        glow = NeonCyan,
                        onOpenImage = onOpenImage,
                    )
                }
            }
        }
    }
}

/**
 * One bundled sample as a tappable port-hole: the image behind a milled
 * chrome ring, lit by its own neon. Decoded off the main thread at
 * quarter resolution — the full image only loads if picked (the editor
 * re-reads the asset through the session-file pipeline).
 */
@Composable
private fun SampleThumb(
    assetPath: String,
    labelRes: Int,
    glow: Color,
    onOpenImage: (Uri) -> Unit,
) {
    val context = LocalContext.current
    val thumb by produceState<ImageBitmap?>(initialValue = null, assetPath) {
        value = withContext(Dispatchers.IO) {
            // A missing/unreadable asset degrades to the placeholder disc,
            // never a crash (the paths are hardcoded next to the assets,
            // but a rename shouldn't take the In room down).
            try {
                context.assets.open(assetPath).use { stream ->
                    BitmapFactory.decodeStream(
                        stream,
                        null,
                        BitmapFactory.Options().apply { inSampleSize = 4 },
                    )
                }?.asImageBitmap()
            } catch (e: java.io.IOException) {
                null
            }
        }
    }
    val label = stringResource(labelRes)
    Box(
        modifier = Modifier
            .size(84.dp)
            .semantics { contentDescription = label }
            .clickable(role = Role.Button) {
                onOpenImage(Uri.parse("file:///android_asset/$assetPath"))
            },
        contentAlignment = Alignment.Center,
    ) {
        Canvas(modifier = Modifier.fillMaxSize()) {
            val outer = size.minDimension / 2f
            val c = Offset(size.width / 2f, size.height / 2f)
            drawCircle(
                brush = Brush.radialGradient(
                    colors = listOf(glow.copy(alpha = 0.35f), Color.Transparent),
                    center = c,
                    radius = outer,
                ),
                radius = outer,
                center = c,
            )
            val ringWidth = outer * 0.14f
            drawCircle(
                brush = chromeSweep(),
                radius = outer * 0.90f - ringWidth / 2f,
                center = c,
                style = Stroke(width = ringWidth),
            )
        }
        // The glass itself, inside the ring. An undecoded sample shows the
        // empty port-hole in panel gunmetal rather than a hole in the UI.
        Box(
            modifier = Modifier
                .size(64.dp)
                .clip(CircleShape)
                .background(MeltPanel),
        ) {
            thumb?.let { image ->
                Image(
                    bitmap = image,
                    contentDescription = null,
                    contentScale = ContentScale.Crop,
                    modifier = Modifier
                        .fillMaxSize()
                        .clip(CircleShape),
                )
            }
        }
    }
}
